#!/usr/bin/env bash

UO_SHARD_NAME="Shadow Age: REBORN"
UO_SHARD_ROOT="http://patch.shadowagereborn.com"
UO_SHARD_PORT="2595"

UO_SHARD_CLIENT="ClassicUO.exe"
UO_SHARD_CLIENT_DIR="ClassicUO"
UO_SHARD_CLIENT_FLAGS="-force_driver 1"

UO_SHARD_LAUNCHER="ClassicUOLauncher.exe"
UO_SHARD_LAUNCHER_DIR="."
UO_SHARD_LAUNCHER_FLAGS="-force_driver 1"

WINETRICKS_PACKAGES=("dotnet48")
